all: Multipliper.v Add.v MUX2.v MUX3.v MUX4.v Register.v ROM.v Datapath.v Controller.v RGB2YUV.v
	vcs testbench.v Multipliper.v Add.v MUX2.v MUX3.v MUX4.v Register.v ROM.v Datapath.v Controller.v RGB2YUV.v -R -full64 -debug_access+all +v2k
